export const ComplaintModelShape = {
  id: "ObjectId|string",
  tokenNumber: "PMC-YYYY-NNNNNN",
  citizenId: "ObjectId|string",
  title: "string",
  category: "string",
  subcategory: "string",
  description: "string",
  locationText: "string",
  wardNumber: "optional string",
  areaName: "optional string",
  nearestLandmark: "optional string",
  priority: "high | medium | low",
  anonymous: "boolean",
  contactOptIn: "boolean",
  contactName: "optional string",
  contactPhone: "optional string",
  contactEmail: "optional string",
  proofImage: "optional { name, mimeType, dataUrl }",
  attachments: ["optional { name, mimeType, dataUrl }"],
  officeType: "department | ward | central_admin",
  divisionName: "optional string",
  sectionName: "optional string",
  routeBucket: "string",
  assignmentReason: "string",
  assignedOfficerId: "optional ObjectId|string",
  assignedOfficerName: "optional string",
  acceptedAt: "optional Date",
  acceptedByOfficerId: "optional ObjectId|string",
  status: "pending | forwarded | in_progress | delayed | solved | escalated | pending_admin_verification | closed_invalid | cannot_solve",
  estimatedCompletionAt: "optional Date|string",
  slaDueAt: "Date",
  firstResponseAt: "optional Date",
  forwardedTo: "optional string",
  forwardedToLabel: "optional string",
  escalated: "boolean",
  delayReason: "optional string",
  citizenRating: "optional number 0-5",
  closureConfirmedAt: "optional Date",
  pointsAwarded: "number",
  validityVerified: "boolean",
  latestComments: ["summary comments"],
  comments: ["embedded comment summaries"],
  history: ["embedded status/action history"],
  createdAt: "Date",
  updatedAt: "Date",
};
